a=int(input('Enter the first value'))
b=int(input('Enter the second value'))
c=int(input('Enter the third value'))
d=int(input('Enter the fourth value'))
e=int(input('Enter the fifth value'))
f=int(input('Enter the sixth value'))
g=int(input('Enter the seventh value'))
h=int(input('Enter the eighth value'))
i=int(input('Enter the nineth value'))
j=int(input('Enter the tenth value'))
mylist=[a,b,c,d,e,f,g,h,i,j]
print(mylist)
sum= sum(mylist)
print('sum of mylist:',sum)